version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.6
    command: --max_allowed_packet=32505856 
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQLDB_USER_PASSWORD}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_HOST=${MYSQLDB_HOST}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}

  app:
    build: ./lwts-app
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - PORT=${NODE_LOCAL_PORT}
      - DB_HOST=${MYSQLDB_HOST}
      - DB_USER=${MYSQLDB_ROOT_USER}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_NAME=${MYSQLDB_DATABASE}
      - DB_PORT=${MYSQLDB_DOCKER_PORT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGID=${OPENAI_ORGID}

volumes:
  db: